version: '3'

services:
  proxy:
    container_name: proxy
    image: proxy:dev
    ports:
      - 443:443
      - 80:80
    depends_on:
      - webapp
  
  webapp:
    container_name: webapp
    image: webapp:dev
    volumes:
      - ./webapp:/app
