project:
  name: example
  version: 0.0.0
  description: An example composify project serving a webapp behind a caddy reverse proxy!
  source: https://github.com/timmypidashev/composify-example
  registry: ghcr.io/timmypidashev/composify-example
  license: MIT
  private: False

containers:
  proxy:
    version: 0.0.0
    description: An example caddy docker container serving as a reverse proxy.
    location: ./proxy
    dev-args:
      - DOMAIN: example.local
    prod-args:
      - DOMAIN: example.com

  webapp:
    version: 0.0.0
    description: An example container running a reflex webapp.
    location: ./webapp
    dev-args:
      - API_URL: https://example.local
    prod-args:
      - API_URL: https://example.com
