project:
  name: example
  version: 0.0.0
  description: An example composify project serving a webapp behind a caddy reverse proxy!
  source: https://github.com/timmypidashev/composify-example
  registry: ghcr.io/timmypidashev/composify-example
  license: MIT
  private: False

containers:
  proxy:
    version: 0.0.0
    description: An example caddy docker container serving as a reverse proxy.
    location: ./proxy
